### ISSUE TITLE
Convert the parsed XML into a Swift Object

### ISSUE THREAD

**Issue by ekahannah** [skiptools/skip-xml#1]
Hi! 
I tried to use the ff function: 
```
 func parseXML(data: Data) throws -> String {
        let node = try XMLNode.parse(data: data, options: [.processNamespaces])
        return node.xmlString() // returns the XML document as a string
    }
```
I received the xml document as a string which is great. 

Wondering if we support setting the XML attribute as a property of swift class or struct? Similar to XMLParserDelegate or XMLParser? I believe that XMLParser is not yet available in Skip so are there any recommendations to parse data from XML as an object and not a string?

Example:
```
class RssItem : NSObject {

var title:String = "";
var link:String = "";

var images:AnyObject = NSMutableArray();

}

**Comment by marcprux** [comment]
The documentation for SkipXML is minimal at this point, but look at the XMLNode API at https://github.com/skiptools/skip-xml/blob/main/Sources/SkipXML/SkipXML.swift#L30 . There are no Codable niceties at this point, but you can use that API to manually create initializers for types you want to deserialize from XML.

Let us know if you encounter issues with the API. It is a very nascent project, and so we'd like your feedback in improving and documenting the API.

BTW, we may implement some of `Foundation.XMLParser` in `SkipFoundation` at some point, but it probably won't happen very soon. So you'll be best off using SkipXML at this point.
